# Generated by Django 4.0.4 on 2022-04-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationtype',
            old_name='studentdate',
            new_name='examtype',
        ),
        migrations.AlterUniqueTogether(
            name='examinationtype',
            unique_together={('examid', 'examtype')},
        ),
    ]
