# Generated by Django 4.0.4 on 2022-04-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentidpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentidpassword',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student3'),
        ),
    ]
