# Generated by Django 4.0.4 on 2022-04-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_exammarklist1'),
    ]

    operations = [
        migrations.CreateModel(
            name='examquestionpaper',
            fields=[
                ('examtype', models.CharField(max_length=50)),
                ('questionpaper', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exammarklist2')),
            ],
        ),
    ]
