# Generated by Django 4.0.4 on 2022-04-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_studentdate_examinationtype_examtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentidpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentpassword', models.CharField(max_length=255)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.admin2')),
            ],
            options={
                'unique_together': {('studentid', 'studentpassword')},
            },
        ),
    ]
