# Generated by Django 4.0.4 on 2022-04-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_studentidpassword_studentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exammarklist1',
        ),
    ]
